'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageCandidates

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''lblAdminName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAdminName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlPosition As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlFaculty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFaculty As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtFullName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFullName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMajor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMajor As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtYearLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtYearLevel As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnAddCandidate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddCandidate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gvCandidates control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvCandidates As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnBack control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnLogout control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.Button
End Class
