'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageVoters

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''lblAdminName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAdminName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pnlMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtADUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtADUsername As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddlFaculty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFaculty As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnAddVoter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddVoter As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''txtUsernameFilter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtUsernameFilter As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddlFacultyFilter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFacultyFilter As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlStatusFilter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlStatusFilter As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnApplyFilter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnApplyFilter As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnClearFilter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnClearFilter As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gvVoters control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvVoters As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnRefresh control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnBack control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnLogout control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.Button
End Class
